config/routes.rb
Hackerjews::Application.routes.draw do
  resources :links, :only => [:index, :new, :create, :edit, :update, :show] do
    resources :comments, :only => [:new, :create]
    resources :votes, :only => [:create]
  end

  resources :comments, :only => [:new, :create] do
    resources :comments, :only => [:new, :create]
    resources :votes, :only => [:create]
  end

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create]
  root :to => 'links#index'
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  content          :string(255)      not null
#  user_id          :integer          not null
#  commentable_id   :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  commentable_type :string(255)
#

#fixme make commentable_type not null

class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  has_many :votes, :as => :votable

  attr_accessible :content

  validates :commentable_id, :presence => true
  validates :content,        :presence => true
  validates :user_id,        :presence => true
end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string(255)      not null
#  title      :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#

GRAVITY = 1.8
TIME_TO_EDIT = 900

class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :votes, :as => :votable

  attr_accessible :title, :url

  before_validation :sanitize

  validates :title, :presence => true
  validates :url, :presence => true, :uniqueness => true
  validates :user_id, :presence => true
  
  #fixme add validation for valid_edit?

  def valid_edit?
    true if (Time.now - created_at) < TIME_TO_EDIT
  end

  def score
     vote_count / ( hours_past + 2) ** GRAVITY
  end

  private
  
  def sanitize
    url = self.url.downcase
    self.url = "http://" + url if !url.match(/^http/)
  end

  def vote_count
    self.votes.count
  end

  def hours_past
    (Time.now - self.created_at)/3600
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  handle          :string(255)      not null
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_many :links
  has_many :comments
  has_many :votes

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessible :email, :handle, :password, :password_confirmation
  has_secure_password

  validates :email, :presence => true, :uniqueness => true, :format => {:with => VALID_EMAIL_REGEX}
  validates :handle, :presence => true, :uniqueness => true
  validates :password, :presence => true, :length => {minimum: 6}
  validates :password_confirmation, :presence => :true

  def karma
    comment_karma + link_karma
  end

  private
  
  def comment_karma
    User.joins(:comments => :votes).where('id' => self.id).sum('votes.direction').to_i
  end

  def link_karma
    User.joins(:links => :votes).where('id' => self.id).sum('votes.direction').to_i
  end

  def sanitize
    self.email = email.downcase
  end
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  link_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ActiveRecord::Base
  attr_accessible :votable, :direction

  belongs_to :user
  belongs_to :link
  belongs_to :votable, :polymorphic => true

  validates_uniqueness_of :user_id, :scope => [:votable_id, :votable_type]
  #fixme validates_numericality_of :direction, :if => Proc.new {|v| v.direction.abs == 1}

  validates :user,         :presence => true
  validates :direction,    :presence => true
  validates :votable,      :presence => true
  validates :votable_type, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authorize, :only => [:new, :create]
  before_filter :load_commentable

  def new
    @comment = Comment.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment])
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = "Thank you for your comment."
      redirect_to link_path(find_link(@commentable))
    else
      render :new
    end
  end

  private
  
  def load_commentable
    if params[:comment_id]
      @commentable = Comment.find(params[:comment_id])
    else
      @commentable = Link.find(params[:link_id])
    end
  end
  
  def find_link(commentable)
    if commentable.is_a? Link
      commentable
    else
      find_link(commentable.commentable)
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :authorize, :only => [:new, :create, :edit, :update]

  def show
    @link = Link.find(params[:id])
    @vote = Vote.new
    if signed_in?
      @comment = Comment.new
    else
      flash.now[:notice] = "Sign in or create an account to leave comments."
    end
  end

  def index
    @links = Kaminari.paginate_array(Link.all.sort_by(&:score).reverse).page(params[:page])
    @vote = Vote.new
  end

  def new
    @link = current_user.links.new
  end

  def create
    @link = current_user.links.new(params[:link])
    if @link.save
      flash[:success] = "Thanks for submitting a link."
      redirect_to links_path
    else
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
    unless @link.valid_edit?
      flash[:error] = "Sorry, you can only edit a link within 15 minutes of its submission."
      redirect_to links_path
    end
  end

  def update
    @link = Link.find(params[:id])
    if @link.update_attributes(params[:link])
      flash[:success] = "You risked it all and gained everything. Congratulations. You've just updated your submission."
      redirect_to links_path
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      flash[:success] = "Welcome back!"
      redirect_to links_path
    else
      flash.now[:error] = "Wrong email or password."
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      flash[:success] = "Welcome!"
      redirect_to links_path
    else
      render :new
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :load_votable
  
  def create
    current_user.votes.create(:votable => @votable, :direction => params[:direction])
    flash[:success] = "Thanks for voting."
    redirect_to :back
  end
  
  private
  
  def load_votable
    if params[:link_id]
      @votable = Link.find(params[:link_id])
    else
      @votable = Comment.find(params[:comment_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def signed_in?
    session[:user_id] ? true : false
  end

  def authorize
    unless signed_in?
      flash[:error] = "Please sign in or create an account."
      redirect_to :back
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def valid_vote?(votable)
    @votable = votable
    !voted? && !own_votable?
  end

  private
  
  def voted?
    Vote.where(:user_id => current_user, :votable_id => @votable, :votable_type => @votable.class).any?
  end

  def own_votable?
    @votable.user_id == current_user.id
  end
end

app/views/comments/_comment.html.haml
%li
  %h2= comment.user.handle
  = comment.content
  - if signed_in?
    = link_to "Reply", new_comment_comment_path(comment)
    - if valid_vote?(comment)
      = render :partial => 'shared/vote', :locals => {:votable => comment}
  %ul= render comment.comments

app/views/comments/_form.html.haml
= form_for [commentable, @comment] do |f|
  .field
    = f.text_area :content
  .actions
    = f.submit "Add comment"

app/views/comments/new.html.haml
%h1 New comment
= render :partial => 'layouts/errors', :locals => {:object => @comment}
= render :partial => 'form', :locals => {:commentable => @commentable}

app/views/layouts/_errors.html.haml
- if object.errors.any?
  .alert.alert-error
    %h3 Something went wrong:
    - object.errors.full_messages.each do |message|
      %li= message

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name.to_s}" }
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "HackerJews", root_path, :class => 'brand'
- if signed_in?
  %ul.nav
    %li.nav= link_to "Submit", new_link_path
  %p.navbar-text.pull-right= "Karma: #{current_user.karma}"
- else
  %ul.nav.pull-right
    %li.nav= link_to "Sign in", new_session_path
    %li.nav= link_to "Sign up", new_user_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "HackerJews"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/links/_form.html.haml
= form_for @link do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit "Submit"

app/views/links/edit.html.haml
%h1 Edit link
= render :partial => 'layouts/errors', :locals => {:object => @link}
= render 'form'

app/views/links/index.html.haml
%ul.unstyled
  - @links.each do |link|
    %li
      = link_to link.title, link.url
      = link_to "Comments", link_path(link)
      - if signed_in?
        - if current_user == link.user && link.valid_edit?
          = link_to "Edit", edit_link_path(link)
        - if valid_vote?(link)
          = render :partial => 'shared/vote', :locals => {:votable => link}
= paginate @links, :theme => 'twitter-bootstrap'

app/views/links/new.html.haml
%h1 Submit link
= render :partial => 'layouts/errors', :locals => {:object => @link}
= render 'form'

app/views/links/show.html.haml
%h1= link_to @link.title, @link.url
= render :partial => 'comments/form', :locals => {:commentable => @link} if signed_in?
%ul= render :partial => @link.comments, :locals => {:commentable => @link}

app/views/shared/_vote.haml
- {"up" => 1, "down" => -1}.each do |direction, value|
  = link_to "",
            polymorphic_path([votable, @vote], :direction => value),
            :method => :post,
            :class => "icon-chevron-#{direction}"

app/views/users/_form.html.haml
= form_for @user do |f|
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :handle
    = f.text_field :handle
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit "Sign up"

app/views/users/new.html.haml
%h1 Sign up
= render :partial => 'layouts/errors', :locals => {:object => @user}
= render 'form'